workspace:
  base: /go
  path: src/github.com/moqmar/gook
pipeline:
  build:
    image: golang
    commands:
    - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static" -s' -o gook -v .
  publish:
    image: appleboy/drone-scp
    host: mo-mar.de
    port: 2244
    secrets: [ ssh_username, ssh_key ]
    target:
    - /static/static/bin/gook
    source:
    - gook
    when:
      branch: master
