workspace:
  base: /go
  path: src/github.com/moqmar/gook
pipeline:
  build:
    image: golang
    commands:
    - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static" -s' -o gook -v .
  publish:
    image: alpine
    secrets: [ webhook_key, file_key ]
    when:
      branch: master
    commands:
    - apk add --no-cache curl
    - curl -H "Content-Type:application/octet-stream" --data "@gook" -qo- "https://gook.mo-mar.de/static/$WEBHOOK_KEY?file=$FILE_KEY" | tee /dev/stderr | grep '^file written:' >/dev/null
