workspace:
  base: /go
  path: src/github.com/moqmar/gook
pipeline:
  build:
    image: golang
    commands:
    - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static" -s' -o gook -v .
  publish:
    image: plugins/s3
    bucket: get
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    source: gook
    target: /
    path_style: true
    endpoint: https://minio.mo-mar.de
    when:
      branch: master
